server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh # payment_route 路由的ID, 没有固定规则但要求唯一，建议配合服务名
          #          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 启用Gateway的负载均衡功能。
          predicates:
            - Path=/payment/get/**   # 断言，路径相匹配的进行路由
            - After=2022-08-08T07:55:15.958+08:00[Asia/Shanghai]
            - Before=2022-08-28T10:55:15.958+08:00[Asia/Shanghai]
            - Between=2022-08-08T07:55:15.958+08:00[Asia/Shanghai],2022-08-28T10:55:15.958+08:00[Asia/Shanghai]
#            - Cookie=user,yao0er4
#            - Header=X-Request-Id,\d+ # 请求头要有 X-Request-Id，并且值为整数的正则表达式
#            - Host=**.yao0er4.com
            - Method=Get
            - Query=number,\d+  # 要有参数名为number 的参数，且值为整数
          filters:
            - AddRequestParameter=X-Request-Id,1024 # 过滤器工厂会在匹配的请求头上加上一对请求参数，名称为X-Request-Id，值为1024

        - id: payment_routh2
          #          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 启用Gateway的负载均衡功能。
          predicates:
            - Path=/payment/lb/**   # 断言，路径相匹配的进行路由
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka