server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka 服务端的实例名称
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: false # false 表示不向服务中心注册自己
    fetch-registry: false # false 表示自己就是注册中心，职责是维护实例，不需要检索服务
    service-url:
      # 设置 与EurekaServer交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka
  server:
    enable-self-preservation: false  # 可以禁用自我保护模式